package index

import (
	"context"
	"path/filepath"
	"strings"

	"github.com/abdul-hamid-achik/codemap/internal/extract"
	"github.com/abdul-hamid-achik/codemap/internal/graph"
	"gopkg.in/yaml.v3"
)

// GitHub workflow YAML is source. Keep other hidden directories excluded and
// use the same rule for indexing, freshness checks, and watcher registration.
func skipHiddenDirectory(name string) bool {
	return strings.HasPrefix(name, ".") && name != ".github"
}

// Reconcile declarative relationships even when the source is unchanged: a
// previously missing link/table may have appeared, or gained an ambiguous twin.
// ponytail: reparse declarative files per index; persist unresolved references
// if profiling shows this bounded, offline pass dominates incremental indexing.
func (ix *Indexer) resolveFormatRelations(ctx context.Context, projectID int64, root string, ni *nodeIndex) error {
	var refs []extract.Reference
	sources := map[string][]byte{}
	for _, n := range ni.nodes {
		if err := ctx.Err(); err != nil {
			return err
		}
		if n.Kind != graph.KindFile || (n.Language != "sql" && n.Language != "yaml" && n.Language != "markdown") {
			continue
		}
		data, oversized, err := readFileUnderLimit(filepath.Join(root, n.FilePath), ix.cfg.MaxFileBytes)
		if err != nil || oversized {
			continue
		}
		hash, err := ix.graph.FileHash(projectID, n.FilePath)
		if err != nil {
			return err
		}
		if hash != sha256hex(data) {
			continue
		}
		fr, err := ix.extractors[n.Language].ExtractFile(n.FilePath, data)
		if err != nil {
			continue
		}
		refs = append(refs, fr.References...)
		sources[n.FilePath] = data
	}
	refs = append(refs, sqlcRelations(root, ni, sources, ix.cfg.MaxFileBytes)...)
	tx, err := ix.graph.BeginTx(ctx)
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()
	_, err = tx.ExecContext(ctx, `DELETE FROM edges WHERE edge_type IN ('reads','writes','documents','depends_on') AND source_id IN (SELECT id FROM nodes WHERE project_id=?)`, projectID)
	if err != nil {
		return err
	}
	if _, err = resolveEdgesTx(tx, refs, ni); err != nil {
		return err
	}
	return tx.Commit()
}

// sqlc's config scopes the SQL inputs and generated Go directory. A matching
// method name alone is insufficient: require the generated-file marker and
// the exact query annotation in that generated source too.
func sqlcRelations(root string, ni *nodeIndex, sources map[string][]byte, maxBytes int) []extract.Reference {
	var refs []extract.Reference
	for file, data := range sources {
		base := strings.ToLower(filepath.Base(file))
		if base != "sqlc.yaml" && base != "sqlc.yml" {
			continue
		}
		var cfg struct {
			SQL []struct {
				Queries any `yaml:"queries"`
				Gen     struct {
					Go struct {
						Out string `yaml:"out"`
					} `yaml:"go"`
				} `yaml:"gen"`
			} `yaml:"sql"`
		}
		if yaml.Unmarshal(data, &cfg) != nil {
			continue
		}
		for _, entry := range cfg.SQL {
			if entry.Gen.Go.Out == "" {
				continue
			}
			out := normalizeSlashPath(joinSlash(parentDir(file), entry.Gen.Go.Out))
			if out == "" && entry.Gen.Go.Out != "." {
				continue
			}
			var inputs []string
			switch q := entry.Queries.(type) {
			case string:
				inputs = append(inputs, q)
			case []any:
				for _, v := range q {
					if s, ok := v.(string); ok {
						inputs = append(inputs, s)
					}
				}
			}
			queryNodes := map[string][]graph.Node{}
			for _, n := range ni.nodes {
				if n.Language != "sql" || n.Kind != graph.KindQuery {
					continue
				}
				for _, input := range inputs {
					pattern := normalizeSlashPath(joinSlash(parentDir(file), input))
					if pattern == "" {
						continue
					}
					match, _ := filepath.Match(pattern, n.FilePath)
					if match || strings.HasPrefix(n.FilePath, pattern+"/") {
						queryNodes[n.Symbol] = append(queryNodes[n.Symbol], n)
						break
					}
				}
			}
			generated := map[string]string{}
			for _, n := range ni.nodes {
				if n.Language != "go" || (n.Kind != graph.KindMethod && n.Kind != graph.KindFunction) || parentDir(n.FilePath) != out {
					continue
				}
				qs := queryNodes[n.Symbol]
				if len(qs) != 1 {
					continue
				}
				body, ok := generated[n.FilePath]
				if !ok {
					b, oversized, err := readFileUnderLimit(filepath.Join(root, n.FilePath), maxBytes)
					if err != nil || oversized {
						continue
					}
					body = string(b)
					generated[n.FilePath] = body
				}
				if !strings.Contains(body, "Code generated by sqlc. DO NOT EDIT.") || !strings.Contains(body, "-- name: "+n.Symbol+" :") {
					continue
				}
				refs = append(refs, extract.Reference{From: n.FQN, ToFQN: qs[0].FQN, Kind: graph.EdgeDependsOn, Line: n.StartLine})
			}
		}
	}
	return refs
}
