package index

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/abdul-hamid-achik/codemap/internal/config"
	"github.com/abdul-hamid-achik/codemap/internal/graph"
)

func TestDeclarativeGraphAndIncrementalLinks(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "schema.sql", "CREATE TABLE sessions (id integer);\n")
	writeFile(t, root, "queries/get.sql", "-- name: GetSession :one\nSELECT * FROM sessions;\n")
	writeFile(t, root, "sqlc.yaml", "version: '2'\nsql:\n  - queries: queries\n    schema: schema.sql\n    gen:\n      go:\n        out: db\n")
	writeFile(t, root, "db/get.sql.go", "// Code generated by sqlc. DO NOT EDIT.\npackage db\n// -- name: GetSession :one\nfunc GetSession() {}\nfunc sessions() {}\n")
	writeFile(t, root, "main.go", "package main\nimport \"example/db\"\nfunc Caller() { db.GetSession() }\n")
	writeFile(t, root, "README.md", "# Sessions\n[Query](queries/get.sql)\n[Future](future.sql)\n")
	writeFile(t, root, ".github/workflows/ci.yml", "jobs:\n  test: {}\n  release:\n    needs: test\n")
	writeFile(t, root, ".hidden/private.yml", "hidden: true\n")
	g, _ := newStores(t)
	pid, err := g.UpsertProject("formats", root, "mixed")
	if err != nil {
		t.Fatal(err)
	}
	ix := New(g, nil, nil, config.DefaultConfig().Index)
	index := func() {
		t.Helper()
		r, err := ix.IndexProject(context.Background(), pid, "formats", root, Options{NoLSP: true})
		if err != nil || len(r.Errors) > 0 {
			t.Fatalf("index=%+v err=%v", r, err)
		}
	}
	index()
	check := func(wantFuture bool) {
		t.Helper()
		nodes, err := g.ProjectNodes(pid)
		if err != nil {
			t.Fatal(err)
		}
		byID := map[int64]graph.Node{}
		for _, n := range nodes {
			byID[n.ID] = n
			if n.FilePath == ".hidden/private.yml" {
				t.Fatal("hidden directory indexed")
			}
		}
		edges, err := g.ProjectEdges(pid)
		if err != nil {
			t.Fatal(err)
		}
		read, generated, workflow, document, future := false, false, false, false, false
		for _, e := range edges {
			a, b := byID[e.SourceID], byID[e.TargetID]
			if e.EdgeType == graph.EdgeReads {
				if b.Kind != graph.KindTable || b.Symbol != "sessions" {
					t.Fatalf("SQL confused with code: %+v", b)
				}
				read = true
				if e.Provenance != graph.ProvName {
					t.Fatal("lexical SQL marked precise")
				}
			}
			if e.EdgeType == graph.EdgeDependsOn && a.Language == "go" && b.Language == "sql" {
				generated = true
			}
			if e.EdgeType == graph.EdgeDependsOn && a.Language == "yaml" {
				workflow = true
			}
			if e.EdgeType == graph.EdgeDocuments && b.FilePath == "queries/get.sql" {
				document = true
			}
			if e.EdgeType == graph.EdgeDocuments && b.FilePath == "future.sql" {
				future = true
			}
			if e.EdgeType == graph.EdgeCalls && (a.Language != "go" || b.Language != "go") {
				t.Fatal("declarative edge leaked into call graph")
			}
		}
		if !read || !generated || !workflow || !document || future != wantFuture {
			t.Fatalf("read=%v sqlc=%v workflow=%v docs=%v future=%v", read, generated, workflow, document, future)
		}
	}
	check(false)
	writeFile(t, root, "future.sql", "CREATE TABLE future (id integer);\n")
	// An unchanged Markdown file must acquire its formerly unresolved link.
	r, err := ix.IndexFiles(context.Background(), pid, "formats", root, []string{"future.sql"}, Options{NoLSP: true})
	if err != nil || len(r.Errors) > 0 {
		t.Fatalf("incremental=%+v %v", r, err)
	}
	check(true)
	writeFile(t, root, "schema.sql", "\n\nCREATE TABLE sessions (id integer);\n")
	index()
	check(true)
	if err := os.Remove(filepath.Join(root, "future.sql")); err != nil {
		t.Fatal(err)
	}
	index()
	check(false)
	writeFile(t, root, ".github/workflows/new.yml", "jobs: {test: {}}\n")
	stale, err := ix.Staleness(pid, root, map[string]bool{"yaml": true, "sql": true, "markdown": true, "go": true})
	if err != nil || stale.New != 1 {
		t.Fatalf("workflow freshness=%+v %v", stale, err)
	}
}
