version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - staticcheck
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-QF1001"
        - "-QF1003"
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        path: _test\.go$
