package app

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// This file installs the portable using-codemap skill (RenderPlaybook
// FormatAgentSkill) behind `codemap agent skill`. The skill is written ONCE to
// the shared skill library (~/.agents/skills, the directory minerva manages and
// omp reads natively) and linked into every detected harness that loads skills
// from its own directory. Like agent setup, no DB/session is opened.
//
// Skill directories verified 2026-10-07: Claude Code ~/.claude/skills, Codex
// $CODEX_HOME/skills (~/.codex), OpenCode $XDG_CONFIG_HOME/opencode/skills,
// Hermes $HERMES_HOME/skills (~/.hermes; its loader follows symlinks), omp
// ~/.agents/skills natively.

// agentSkillName is the skill's directory and frontmatter name.
const agentSkillName = "using-codemap"

// agentSkillMarker identifies a SKILL.md codemap wrote, so a reinstall may
// replace it while a hand-written skill of the same name is left alone.
const agentSkillMarker = "<!-- generated by `codemap agent skill`; run it again to update -->"

// SkillOptions controls one `codemap agent skill` run.
type SkillOptions struct {
	Harnesses []string // explicit targets ("all" for every known one); empty = every detected harness
	Dir       string   // shared skill library; default ~/.agents/skills
	Copy      bool     // copy the skill into harness dirs instead of symlinking
	Force     bool     // replace a same-named skill codemap did not write
	Remove    bool     // uninstall: remove only what codemap wrote
	DryRun    bool     // report planned changes, touch nothing
}

// SkillTarget is the outcome for one destination. Action is one of
// created|updated|unchanged|linked|copied|removed|native|skipped.
type SkillTarget struct {
	Harness string `json:"harness"`
	Path    string `json:"path"`
	Action  string `json:"action"`
	Reason  string `json:"reason,omitempty"`
}

// SkillReport is the machine-readable result of `codemap agent skill`.
type SkillReport struct {
	Skill   string        `json:"skill"`
	Action  string        `json:"action"`
	Targets []SkillTarget `json:"targets,omitempty"`
	DryRun  bool          `json:"dry_run,omitempty"`
}

// skillHarness is a harness that loads skills from a directory. An empty
// skillsDir means it reads the shared library natively.
type skillHarness struct {
	name      string
	home      func() string // its presence means the harness is installed
	skillsDir func() string
	skip      func() string // non-empty: why a detected (not requested) harness is skipped
}

func envOr(key, fallback string) string {
	if v := strings.TrimSpace(os.Getenv(key)); v != "" {
		return v
	}
	return fallback
}

var skillHarnesses = []skillHarness{
	{
		name:      "claude",
		home:      func() string { return filepath.Join(homeDir(), ".claude") },
		skillsDir: func() string { return filepath.Join(homeDir(), ".claude", "skills") },
		skip:      claudePluginSkip,
	},
	{
		name:      "codex",
		home:      func() string { return envOr("CODEX_HOME", filepath.Join(homeDir(), ".codex")) },
		skillsDir: func() string { return filepath.Join(envOr("CODEX_HOME", filepath.Join(homeDir(), ".codex")), "skills") },
	},
	{
		name:      "opencode",
		home:      func() string { return filepath.Join(configHome(), "opencode") },
		skillsDir: func() string { return filepath.Join(configHome(), "opencode", "skills") },
	},
	{
		name: "hermes",
		home: func() string { return envOr("HERMES_HOME", filepath.Join(homeDir(), ".hermes")) },
		skillsDir: func() string {
			return filepath.Join(envOr("HERMES_HOME", filepath.Join(homeDir(), ".hermes")), "skills")
		},
	},
	{
		name:      "omp",
		home:      func() string { return filepath.Join(homeDir(), ".omp") },
		skillsDir: func() string { return "" },
	},
}

// SkillHarnessNames lists the harness names `codemap agent skill` accepts.
func SkillHarnessNames() []string {
	names := []string{"agents"}
	for _, h := range skillHarnesses {
		names = append(names, h.name)
	}
	return append(names, "all")
}

// claudePluginSkip skips Claude Code when the codemap plugin is installed: the
// plugin already ships its own using-codemap skill.
func claudePluginSkip() string {
	b, err := os.ReadFile(filepath.Join(homeDir(), ".claude", "plugins", "installed_plugins.json"))
	if err == nil && strings.Contains(string(b), `"codemap@`) {
		return "the codemap Claude Code plugin already provides using-codemap (pass --harness claude to link it anyway)"
	}
	return ""
}

// DefaultSkillDir is the shared skill library: $MINERVA_AGENTS_DIR/skills when
// minerva points elsewhere, else ~/.agents/skills.
func DefaultSkillDir() string {
	if d := strings.TrimSpace(os.Getenv("MINERVA_AGENTS_DIR")); d != "" {
		return filepath.Join(d, "skills")
	}
	return filepath.Join(homeDir(), ".agents", "skills")
}

// InstallAgentSkill writes the using-codemap skill to the shared library and
// links it into each selected harness (or removes what it wrote, with Remove).
func InstallAgentSkill(opts SkillOptions) (SkillReport, error) {
	targets, err := selectSkillHarnesses(opts.Harnesses)
	if err != nil {
		return SkillReport{}, err
	}
	lib := opts.Dir
	if lib == "" {
		lib = DefaultSkillDir()
	}
	canonical := filepath.Join(lib, agentSkillName)
	rep := SkillReport{Skill: filepath.Join(canonical, "SKILL.md"), DryRun: opts.DryRun}

	if opts.Remove {
		for _, t := range targets {
			rep.Targets = append(rep.Targets, removeSkillLink(t, canonical, opts.DryRun))
		}
		rep.Action = removeOwned(canonical, opts.DryRun)
		return rep, nil
	}

	content := RenderPlaybook(FormatAgentSkill)
	action, err := writeCanonicalSkill(canonical, content, opts)
	if err != nil {
		return rep, err
	}
	rep.Action = action
	if action == "skipped" {
		return rep, fmt.Errorf("%s exists and was not written by codemap; re-run with --force to replace it", canonical)
	}
	for _, t := range targets {
		rep.Targets = append(rep.Targets, linkSkill(t, canonical, content, opts))
	}
	return rep, nil
}

// selectedHarness is one resolved target; requested means the user named it.
type selectedHarness struct {
	skillHarness
	requested bool
}

func selectSkillHarnesses(names []string) ([]selectedHarness, error) {
	var out []selectedHarness
	if len(names) == 0 {
		for _, h := range skillHarnesses {
			if dirExists(h.home()) {
				out = append(out, selectedHarness{skillHarness: h})
			}
		}
		return out, nil
	}
	want := map[string]bool{}
	for _, n := range names {
		n = strings.ToLower(strings.TrimSpace(n))
		switch n {
		case "", "agents":
			continue
		case "all":
			for _, h := range skillHarnesses {
				want[h.name] = true
			}
			continue
		}
		known := false
		for _, h := range skillHarnesses {
			known = known || h.name == n
		}
		if !known {
			return nil, fmt.Errorf("unknown harness %q — valid: %s", n, strings.Join(SkillHarnessNames(), ", "))
		}
		want[n] = true
	}
	for _, h := range skillHarnesses {
		if want[h.name] {
			out = append(out, selectedHarness{skillHarness: h, requested: true})
		}
	}
	return out, nil
}

// writeCanonicalSkill writes SKILL.md into the shared library. It returns
// skipped when a skill codemap did not write already holds the name.
func writeCanonicalSkill(dir, content string, opts SkillOptions) (string, error) {
	path := filepath.Join(dir, "SKILL.md")
	orig, err := os.ReadFile(path)
	switch {
	case err == nil && string(orig) == content:
		return "unchanged", nil
	case err == nil && !strings.Contains(string(orig), agentSkillMarker) && !opts.Force:
		return "skipped", nil
	case err != nil && !errors.Is(err, fs.ErrNotExist):
		return "", err
	}
	action := "created"
	if err == nil {
		action = "updated"
	}
	if opts.DryRun {
		return action, nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	return action, os.WriteFile(path, []byte(content), 0o644)
}

// linkSkill places the skill in one harness's skills dir: a relative symlink to
// the shared library (a copy with Copy, or when symlinks are unavailable).
func linkSkill(t selectedHarness, canonical, content string, opts SkillOptions) SkillTarget {
	out := SkillTarget{Harness: t.name}
	dir := t.skillsDir()
	if dir == "" {
		out.Path, out.Action, out.Reason = filepath.Dir(canonical), "native", "reads the shared skill library directly"
		return out
	}
	if !t.requested && t.skip != nil {
		if why := t.skip(); why != "" {
			out.Path, out.Action, out.Reason = filepath.Join(dir, agentSkillName), "skipped", why
			return out
		}
	}
	dst := filepath.Join(dir, agentSkillName)
	out.Path = dst
	if samePath(dir, filepath.Dir(canonical)) {
		out.Action, out.Reason = "native", "this harness's skills dir is the shared library"
		return out
	}

	state := skillDestState(dst, canonical)
	switch {
	case state == destOurLink && !opts.Copy:
		out.Action = "unchanged"
		return out
	case state == destForeign && !opts.Force:
		out.Action, out.Reason = "skipped", "a "+agentSkillName+" skill codemap did not write is already there (--force replaces it)"
		return out
	}
	if opts.Copy {
		if state == destOurCopy {
			if b, err := os.ReadFile(filepath.Join(dst, "SKILL.md")); err == nil && string(b) == content {
				out.Action = "unchanged"
				return out
			}
		}
		out.Action = "copied"
	} else {
		out.Action = "linked"
	}
	if opts.DryRun {
		return out
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		out.Action, out.Reason = "skipped", err.Error()
		return out
	}
	if state != destAbsent {
		if err := os.RemoveAll(dst); err != nil {
			out.Action, out.Reason = "skipped", err.Error()
			return out
		}
	}
	if !opts.Copy {
		target := canonical
		if rel, err := filepath.Rel(dir, canonical); err == nil {
			target = rel
		}
		if err := os.Symlink(target, dst); err == nil {
			return out
		}
		out.Action, out.Reason = "copied", "symlinks are unavailable here; copied instead"
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		out.Action, out.Reason = "skipped", err.Error()
		return out
	}
	if err := os.WriteFile(filepath.Join(dst, "SKILL.md"), []byte(content), 0o644); err != nil {
		out.Action, out.Reason = "skipped", err.Error()
	}
	return out
}

type skillDest int

const (
	destAbsent  skillDest = iota
	destOurLink           // symlink resolving to the shared library's skill
	destOurCopy           // a codemap-written skill (copy, or a link elsewhere to one)
	destForeign           // anything else
)

func skillDestState(dst, canonical string) skillDest {
	fi, err := os.Lstat(dst)
	if err != nil {
		return destAbsent
	}
	if fi.Mode()&os.ModeSymlink != 0 {
		if resolved, err := filepath.EvalSymlinks(dst); err == nil {
			if want, err := filepath.EvalSymlinks(canonical); err == nil && resolved == want {
				return destOurLink
			}
		}
	}
	if b, err := os.ReadFile(filepath.Join(dst, "SKILL.md")); err == nil && strings.Contains(string(b), agentSkillMarker) {
		return destOurCopy
	}
	return destForeign
}

func removeSkillLink(t selectedHarness, canonical string, dry bool) SkillTarget {
	out := SkillTarget{Harness: t.name}
	dir := t.skillsDir()
	if dir == "" {
		out.Path, out.Action = filepath.Dir(canonical), "native"
		return out
	}
	out.Path = filepath.Join(dir, agentSkillName)
	if samePath(dir, filepath.Dir(canonical)) {
		out.Action = "native"
		return out
	}
	out.Action = removeOwned(out.Path, dry)
	return out
}

// removeOwned deletes path only when codemap wrote it (a link to its skill or a
// directory holding its marker). It reports removed, absent or skipped.
func removeOwned(path string, dry bool) string {
	fi, err := os.Lstat(path)
	if err != nil {
		return "absent"
	}
	owned := false
	if b, err := os.ReadFile(filepath.Join(path, "SKILL.md")); err == nil && strings.Contains(string(b), agentSkillMarker) {
		owned = true
	}
	if fi.Mode()&os.ModeSymlink != 0 {
		if _, err := os.Stat(path); err != nil {
			// a dangling link left by an earlier install (its library moved)
			if target, err := os.Readlink(path); err == nil && filepath.Base(target) == agentSkillName {
				owned = true
			}
		}
	}
	if !owned {
		return "skipped"
	}
	if dry {
		return "removed"
	}
	if fi.Mode()&os.ModeSymlink != 0 {
		if err := os.Remove(path); err != nil {
			return "skipped"
		}
		return "removed"
	}
	if err := os.RemoveAll(path); err != nil {
		return "skipped"
	}
	return "removed"
}

func samePath(a, b string) bool {
	ra, errA := filepath.EvalSymlinks(a)
	rb, errB := filepath.EvalSymlinks(b)
	if errA != nil || errB != nil {
		return filepath.Clean(a) == filepath.Clean(b)
	}
	return ra == rb
}
