package app

import (
	"regexp"
	"strings"
)

// This file holds the ONE canonical "when to use codemap" playbook and its
// per-harness renderers. The prose body is built ON TOP of docs.go (it embeds
// Docs("workflow") and Docs("accuracy") verbatim) so there is a single source of
// truth for the workflow/accuracy guidance; only the short tool-selection reflex
// (playbookPreamble) lives here. `codemap agent setup`/`playbook` render this into
// each harness's native format, and the checked-in Claude Code SKILL.md is pinned
// byte-for-byte to RenderPlaybook(FormatClaudeSkill) by playbook_test.go.

// playbookDescription is the one-sentence "why this exists" used verbatim in the
// Claude skill and Cursor rule frontmatter (agent-requested activation).
const playbookDescription = "When answering structural code questions (callers, blast radius, tests covering a change, where to start reading), use the codemap_* tools instead of grep/Read; run codemap_review after edits."

// playbookPreamble is the tool-selection reflex: the short "reach for codemap"
// guidance an agent should internalize before it starts reading files. It names
// concrete codemap_<tool> tokens (never a bare "codemap_*") so the CLI renderer
// can rewrite every one of them into its `codemap <name>` command form.
const playbookPreamble = `For structural code questions — who calls X, what breaks if I change Y, where do I
start reading, what tests cover this — reach for codemap before grep or opening
files: if answering would mean reading more than 2 files, call codemap_context (or
codemap_context_batch) first. codemap is a precomputed code graph fused with
semantic search, exposed as codemap_context, codemap_impact and friends over MCP
(and as codemap … --json on the CLI).

Map the loop to the tools:
  - orient on a repo    -> codemap_read_order (entrypoints + hubs, ranked)
  - locate              -> codemap_semantic (by meaning) · codemap_find (by name) · codemap_grep (exact text: a literal, error string, route, env var) · codemap_explore (fuzzy intent → oriented structure)
  - resolve a file:line -> codemap_symbol_at (a stack trace / diff hunk / grep hit → a selector; batch positions:[…] for a whole trace)
  - orient on a file    -> codemap_file_context (symbol outline + file impact + related files in one call)
  - understand          -> codemap_context, codemap_impact, codemap_source
  - before a risky edit -> codemap_risk, codemap_file_impact, codemap_dependencies, codemap_related_files
  - after every edit    -> codemap_review (it names the tests to run and folds one risk band)
  - calibrate trust     -> codemap_coverage (per-file precise call-graph coverage)

Trust the honesty signals on every result: stale (reindex first), call_graph
(resolved/name/unresolved/none), resolution, and the *_total caps. When a name is
ambiguous the response already carries candidates:[…] and accepts a selector, so
pick one definition from those instead of a second lookup. Prefer
codemap_index --precise for exact call edges — it is the only complete call graph for
TypeScript and JavaScript (the default index has same-file and imported-binding
candidates only) and the only call graph for Python.`

// PlaybookFormat selects a harness-native rendering of the canonical playbook.
type PlaybookFormat string

const (
	// FormatClaudeSkill renders a Claude Code skill (YAML frontmatter + body).
	FormatClaudeSkill PlaybookFormat = "claude-skill"
	// FormatCursorRule renders a Cursor .mdc rule (frontmatter + body).
	FormatCursorRule PlaybookFormat = "cursor-rule"
	// FormatMarkdownSection renders an idempotent marked block for the MCP
	// harnesses' guidance files (AGENTS.md, GEMINI.md, .clinerules, .rules, …).
	FormatMarkdownSection PlaybookFormat = "markdown"
	// FormatMarkdownSectionCLI is the no-MCP variant: the same body with every
	// codemap_<tool> rewritten to its `codemap <name> --json` CLI form, for aider
	// CONVENTIONS.md and any AGENTS.md-reading harness without MCP.
	FormatMarkdownSectionCLI PlaybookFormat = "markdown-cli"
	// FormatAgentSkill renders a portable Agent Skills SKILL.md for any harness
	// that loads skills from a directory (~/.agents/skills, Codex, OpenCode,
	// Hermes, omp, Claude Code): the canonical body plus a "Calling codemap"
	// section, so one file works whether or not the codemap MCP server is
	// connected. `codemap agent skill` installs it.
	FormatAgentSkill PlaybookFormat = "skill"
)

const (
	// markerBegin/markerEnd fence the generated block so re-runs replace it in
	// place (idempotent) and hand-edits inside it are detectable.
	markerBegin       = "<!-- codemap:begin (generated by 'codemap agent setup'; do not edit inside markers) -->"
	markerEnd         = "<!-- codemap:end -->"
	markerBeginPrefix = "<!-- codemap:begin"
)

// PlaybookMarkdown is the ONE canonical playbook body: the reflex preamble plus
// the workflow and accuracy topics straight from docs.go, so the guidance can
// never fork from what codemap_docs teaches.
func PlaybookMarkdown() string {
	return playbookPreamble +
		"\n\n## The workflow\n\n" + strings.TrimRight(Docs("workflow"), "\n") +
		"\n\n## Accuracy and honesty signals\n\n" + strings.TrimRight(Docs("accuracy"), "\n") + "\n"
}

// agentSkillDescription is the portable skill's frontmatter description: the
// trigger a harness matches against the task. It names both surfaces because the
// skill is installed where no MCP server may be connected.
const agentSkillDescription = "Use for structural code questions (who calls X, what breaks if Y changes, which tests cover a change, where to start reading a repo) before grep or opening files, and run a codemap review after edits. Works through the codemap_* MCP tools or the codemap CLI with --json."

// agentSkillCalling is the portable skill's preamble: how to reach codemap with
// or without the MCP server, and how to make sure the repo is indexed. The CLI
// mapping is the rule cliify applies (pinned against the registered commands
// by TestCliifyMapsToRegisteredCommands).
const agentSkillCalling = "## Calling codemap\n\n" +
	"If codemap_* tools are in your tool list, use them. Otherwise run the CLI from\n" +
	"the repository: every codemap_<tool> below is `codemap <tool> --json` with\n" +
	"underscores turned into dashes (codemap_file_impact is `codemap file-impact --json`),\n" +
	"codemap_context_batch is `codemap context <a> <b> --json`, and the MCP path\n" +
	"parameter is `-C <dir>`.\n\n" +
	"Before the first question in a repository, check the index with\n" +
	"`codemap status --json`. When registered is false or nodes is 0, run\n" +
	"`codemap index` (add --precise for exact TypeScript/JavaScript/Python call edges\n" +
	"when the language server is installed); when a result says stale, reindex first.\n" +
	"CLI exit codes: 0 answered, 2 not found, 3 index missing, 6 a review/risk gate failed.\n\n"

// mcpToolRe matches a codemap_<tool> MCP token so the CLI renderer can rewrite it.
var mcpToolRe = regexp.MustCompile(`codemap_([a-z][a-z_]*)`)

// cliToolOverrides maps codemap_<tool> MCP names whose CLI form is NOT a
// mechanical dash-rename of the tool name onto the real `codemap <cmd>` to
// use instead. Every other taught tool name matches an actual registered
// cobra command 1:1 after underscores become dashes (pinned by
// TestCliifyMapsToRegisteredCommands in cmd/codemap); this table exists only
// for the exceptions.
//
//   - context_batch: there is no `codemap context-batch` command — the batch
//     form is the multi-arg `codemap context <s1> <s2> …` (see contextCmd's
//     Use: "context [<symbol>...]" in cmd/codemap/query.go).
var cliToolOverrides = map[string]string{
	"context_batch": "context",
}

// cliify rewrites every codemap_<tool> MCP token into its `codemap <name>` CLI
// command form (underscores become dashes, unless cliToolOverrides says
// otherwise) so the no-MCP playbook never mentions a tool the harness can't
// call, while still sourcing its wording from the one canonical body. A final
// sweep guarantees no stray "codemap_" survives.
func cliify(s string) string {
	s = mcpToolRe.ReplaceAllStringFunc(s, func(m string) string {
		name := strings.TrimPrefix(m, "codemap_")
		if cmd, ok := cliToolOverrides[name]; ok {
			return "codemap " + cmd
		}
		return "codemap " + strings.ReplaceAll(name, "_", "-")
	})
	return strings.ReplaceAll(s, "codemap_", "codemap ")
}

// RenderPlaybook renders the canonical playbook in a harness-native format.
func RenderPlaybook(f PlaybookFormat) string {
	switch f {
	case FormatClaudeSkill:
		return "---\nname: using-codemap\ndescription: " + playbookDescription + "\n---\n\n" + PlaybookMarkdown()
	case FormatAgentSkill:
		return "---\nname: using-codemap\ndescription: " + agentSkillDescription + "\n---\n\n" + agentSkillMarker + "\n\n" + agentSkillCalling + PlaybookMarkdown()
	case FormatCursorRule:
		return "---\ndescription: " + playbookDescription + "\nalwaysApply: false\n---\n\n" + PlaybookMarkdown()
	case FormatMarkdownSectionCLI:
		return markerBegin + "\n## Using codemap (CLI, no MCP)\n\n" + cliify(PlaybookMarkdown()) + "\n" + markerEnd + "\n"
	case FormatMarkdownSection:
		fallthrough
	default:
		return markerBegin + "\n## Using codemap\n\n" + PlaybookMarkdown() + "\n" + markerEnd + "\n"
	}
}
