/* Copyright © 2026 abdul hamid <abdulachik@icloud.com> */

import { app, BrowserWindow, Menu, shell, nativeTheme } from 'electron'
import { existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { createRuntime } from './runtime.mjs'
import { Settings } from './settings.mjs'

const here = path.dirname(fileURLToPath(import.meta.url))
const appRoot = path.resolve(here, '..')
const isDev = process.argv.includes('--dev') || process.argv.includes('--devtools')
// Generated by `npm run icons` from docs/public/mark.svg.
const appIcon = path.join(appRoot, 'build', process.platform === 'win32' ? 'icon.ico' : 'icon.png')

let win = null
let settings = null
let runtime = null

function createWindow() {
  win = new BrowserWindow({
    width: 1560,
    height: 980,
    minWidth: 1080,
    minHeight: 680,
    title: 'Codemap Studio',
    backgroundColor: '#0a0c0f',
    show: false,
    icon: existsSync(appIcon) ? appIcon : undefined,
    titleBarStyle: process.platform === 'darwin' ? 'hiddenInset' : 'default',
    trafficLightPosition: { x: 16, y: 18 },
    webPreferences: {
      preload: path.join(here, 'preload.mjs'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
      spellcheck: false,
    },
  })

  win.once('ready-to-show', () => win.show())
  win.loadFile(path.join(appRoot, 'renderer', 'index.html'))
  if (isDev) win.webContents.openDevTools({ mode: 'detach' })

  win.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:/.test(url)) shell.openExternal(url)
    return { action: 'deny' }
  })
  win.on('closed', () => {
    win = null
  })
}

function buildMenu() {
  const isMac = process.platform === 'darwin'
  const goto = (view) => () => runtime?.send('ui:goto', { view })
  const template = [
    ...(isMac ? [{ role: 'appMenu' }] : []),
    { role: 'fileMenu' },
    { role: 'editMenu' },
    {
      label: 'View',
      submenu: [
        { label: 'Command palette', accelerator: 'CmdOrCtrl+K', click: () => runtime?.send('ui:palette', {}) },
        { label: 'Dashboard', accelerator: 'CmdOrCtrl+1', click: goto('dashboard') },
        { label: 'Unified search', accelerator: 'CmdOrCtrl+2', click: goto('search') },
        { label: 'Graph explorer', accelerator: 'CmdOrCtrl+3', click: goto('graph') },
        { label: 'Source browser', accelerator: 'CmdOrCtrl+4', click: goto('source') },
        { label: 'Review desk', accelerator: 'CmdOrCtrl+5', click: goto('review') },
        { label: 'Architecture map', accelerator: 'CmdOrCtrl+6', click: goto('map') },
        { label: 'Feature catalog', accelerator: 'CmdOrCtrl+7', click: goto('catalog') },
        { label: 'MCP inspector', accelerator: 'CmdOrCtrl+8', click: goto('mcp') },
        { type: 'separator' },
        { role: 'reload' },
        { role: 'togglefullscreen' },
      ],
    },
    { role: 'windowMenu' },
  ]
  Menu.setApplicationMenu(Menu.buildFromTemplate(template))
}

app.whenReady().then(() => {
  settings = new Settings(app.getPath('userData'))
  runtime = createRuntime({ appRoot, settings, getWin: () => win, isDev })
  nativeTheme.themeSource = settings.data.theme === 'light' ? 'light' : 'dark'
  // In dev the Dock would otherwise show Electron's default atom.
  if (process.platform === 'darwin' && app.dock && existsSync(appIcon)) app.dock.setIcon(appIcon)
  runtime.registerIPC()
  buildMenu()
  createWindow()

  // warm binary + PATH resolution so the first feature run is fast
  runtime.binary().catch(() => {})

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('before-quit', () => {
  runtime?.stopDaemon()
  settings?.flush()
})

app.on('window-all-closed', () => {
  settings?.flush()
  if (process.platform !== 'darwin') app.quit()
})

process.on('uncaughtException', (err) => {
  runtime?.send('app:error', { message: err?.message || String(err), stack: err?.stack || '' })
})
