#!/usr/bin/env bash
# Renders a codemap review v1 JSON report (schemas/codemap.review.v1.schema.json
# in the codemap repo) into a sticky-comment-ready Markdown body.
#
# Called by: action.yml step id=render; gitlab/codemap-review.yml (curled
# down and invoked unmodified). Its output (comment-path) also feeds
# write-summary.sh (action.yml only) — the job-summary and sticky-PR-comment
# surfaces intentionally share this one rendering pass.
#
# Deliberately plain bash + jq (no Node) so the exact same script runs
# unmodified from the GitLab CI mirror (gitlab/codemap-review.yml).
#
# Usage: REVIEW_JSON_PATH=<path> ./render-comment.sh
#        ./render-comment.sh <path-to-review.json>
#
# Writes the rendered Markdown to $out (see below) and, when running inside a
# GitHub Actions step, exposes it as the `comment-path` step output.
set -euo pipefail

REVIEW_JSON="${1:-${REVIEW_JSON_PATH:-}}"
if [[ -z "$REVIEW_JSON" || ! -f "$REVIEW_JSON" ]]; then
  echo "usage: render-comment.sh <review.json>  (or export REVIEW_JSON_PATH)" >&2
  exit 1
fi

ACTION_VERSION="${CODEMAP_ACTION_VERSION:-dev}"
COMMIT_SHA="${GITHUB_SHA:-unknown}"
MARKER='<!-- codemap-review-action:marker -->'
MAX_BYTES="${CODEMAP_COMMENT_MAX_BYTES:-60000}" # GitHub's hard cap is 65536
OUT_DIR="${RUNNER_TEMP:-$(dirname "$REVIEW_JSON")}"
OUT="${OUT_DIR}/codemap-review-comment.md"

FILES_CAP="${CODEMAP_FILES_CAP:-25}"
SYMBOLS_CAP="${CODEMAP_SYMBOLS_CAP:-25}"
BLAST_CAP="${CODEMAP_BLAST_CAP:-15}"
UNTESTED_CAP="${CODEMAP_UNTESTED_CAP:-50}"
HOTSPOTS_CAP="${CODEMAP_HOTSPOTS_CAP:-25}"

emit_output() {
  # $1 = rendered file path
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    echo "comment-path=$1" >> "$GITHUB_OUTPUT"
  fi
}

j() { jq -r "$1" "$REVIEW_JSON"; }
jraw() { jq -c "$1" "$REVIEW_JSON"; }

# --- schema_version gate: fail soft, never crash on an unknown shape --------
schema_version="$(j '.schema_version // "absent"')"
if [[ "$schema_version" != "1" ]]; then
  {
    echo "$MARKER"
    echo "### codemap review"
    echo
    echo "> codemap-action ${ACTION_VERSION} doesn't understand this codemap version's"
    echo "> review schema (\`schema_version\`: \`${schema_version}\`, expected \`1\`)."
    echo "> Update this action to a version that supports it, or pin an older"
    echo "> \`version\` input that emits schema v1."
    echo
    echo "<sub>generated by codemap-action ${ACTION_VERSION} · commit \`${COMMIT_SHA}\`</sub>"
  } > "$OUT"
  emit_output "$OUT"
  echo "codemap-action: schema_version '${schema_version}' is not 1 — rendered a fail-soft notice instead of the full report"
  exit 0
fi

# --- pull scalar fields ------------------------------------------------------
project="$(j '.project // "?"')"
mode="$(j '.mode // "?"')"
since="$(j '.since // empty')"
is_repo="$(j '.is_repo')"
indexed="$(j '.indexed')"
note="$(j '.note // empty')"
stale="$(j '.stale // false')"
resolution="$(j '.resolution // empty')"
call_graph="$(j '.call_graph // empty')"
risk_present="$(j 'if has("risk") then "true" else "false" end')"
deletion_present="$(j 'if has("deletion_analysis") then "true" else "false" end')"
analysis_complete="$(j 'if .analysis_complete == true then "true" elif .analysis_complete == false then "false" else "unknown" end')"
total_symbols="$(j '.total_symbols // ((.changed_symbols // []) | length)')"
analyzed_symbols="$(j '.analyzed_symbols // "unknown"')"
truncated_symbols="$(j '.truncated_symbols // "unknown"')"
partial_errors_count="$(j '(.partial_errors // []) | length')"
partial_errors_truncated="$(j '.partial_errors_truncated // 0')"

changed_files_count="$(j '(.changed_files // []) | length')"
changed_symbols_count="$(j '(.changed_symbols // []) | length')"
blast_radius_count="$(j '(.blast_radius // []) | length')"
covering_tests_count="$(j '(.covering_tests // []) | length')"
untested_count="$(j '(.untested_symbols // []) | length')"
hotspots_count="$(j '(.hotspots // []) | length')"
test_commands_count="$(j '(.test_commands // []) | length')"

md_escape() {
  # Escape markdown table-breaking pipe characters. Paths/symbols are the
  # only free-text fields that land in table cells.
  printf '%s' "${1//|/\\|}"
}

mode_line() {
  case "$mode" in
    since) printf 'Mode: `since %s`' "$since" ;;
    staged) printf 'Mode: `staged` (the git index)' ;;
    working) printf 'Mode: `working` (whole working tree: staged + unstaged + untracked)' ;;
    *) printf 'Mode: `%s`' "$mode" ;;
  esac
}

render_header() {
  echo "### codemap review"
  echo
  echo "Project: \`${project}\` · $(mode_line)"
  echo
}

render_analysis_warning() {
  if [[ "$analysis_complete" == "true" ]]; then
    return
  fi

  if [[ "$analysis_complete" == "false" ]]; then
    printf '> **⚠️ Incomplete analysis.** codemap analyzed `%s` of `%s` mapped symbol(s); `%s` were truncated.\n' \
      "$analyzed_symbols" "$total_symbols" "$truncated_symbols"
  else
    printf '%s\n' '> **⚠️ Analysis completeness unknown.** This schema-v1 report does not declare `analysis_complete` (it may come from an older codemap release).'
  fi
  if [[ "$partial_errors_count" -gt 0 || "$partial_errors_truncated" -gt 0 ]]; then
    printf '> It reports `%s` partial error(s) and `%s` additional omitted error(s); inspect the raw review JSON for details.\n' \
      "$partial_errors_count" "$partial_errors_truncated"
  fi
  echo "> Blast-radius, test-coverage, and risk results below may describe only the successfully analyzed subset."
  echo
}

render_not_repo_or_indexed() {
  if [[ "$is_repo" != "true" ]]; then
    echo "> **Not a git repository.** codemap review needs git to compute a diff — nothing to show."
    echo
    return 0
  fi
  if [[ "$indexed" != "true" ]]; then
    echo "> **Project not indexed.** Run \`codemap index\` for blast radius and test selection. Showing the raw changed-file list only."
    echo
    render_changed_files
    return 0
  fi
  return 1
}

render_changed_files() {
  if [[ "$changed_files_count" -eq 0 ]]; then
    echo "_No changed files._"
    echo
    return
  fi
  echo "**Files touched** (${changed_files_count})"
  echo
  echo "| File | Status | Symbols |"
  echo "|---|---|---|"
  local i=0
  while IFS=$'\t' read -r path status symbols; do
    i=$((i + 1))
    [[ "$i" -gt "$FILES_CAP" ]] && break
    printf '| `%s` | %s | %s |\n' "$(md_escape "$path")" "$status" "$symbols"
  done < <(jq -r '(.changed_files // [])[] | [.path, .status, (.symbols // 0)] | @tsv' "$REVIEW_JSON")
  if [[ "$changed_files_count" -gt "$FILES_CAP" ]]; then
    echo
    echo "_+$((changed_files_count - FILES_CAP)) more file(s) not shown._"
  fi
  echo
}

render_changed_symbols() {
  if [[ "$changed_symbols_count" -eq 0 ]]; then
    echo "_No changed symbols mapped to indexed code (comments, imports, or unindexed/untracked files)._"
    echo
    return
  fi
  echo "**Changed symbols** (${changed_symbols_count})"
  echo
  echo "| Symbol | Kind | Location |"
  echo "|---|---|---|"
  local i=0
  while IFS=$'\t' read -r fqn kind file line; do
    i=$((i + 1))
    [[ "$i" -gt "$SYMBOLS_CAP" ]] && break
    printf '| `%s` | %s | `%s:%s` |\n' "$(md_escape "$fqn")" "$kind" "$(md_escape "$file")" "$line"
  done < <(jq -r '(.changed_symbols // [])[] | [(.fqn // .symbol), .kind, .file, .start_line] | @tsv' "$REVIEW_JSON")
  if [[ "$changed_symbols_count" -gt "$SYMBOLS_CAP" ]]; then
    echo
    echo "_+$((changed_symbols_count - SYMBOLS_CAP)) more symbol(s) not shown._"
  fi
  echo
}

render_blast_radius() {
  echo "**Blast radius**: ${blast_radius_count} symbol(s) reachable from this diff, ${covering_tests_count} covering test(s)"
  echo
  if [[ "$blast_radius_count" -eq 0 ]]; then
    echo
    return
  fi
  echo "Shallowest first (server-sorted by hop depth):"
  echo
  echo "| Symbol | Kind | Location | Depth |"
  echo "|---|---|---|---|"
  local i=0
  while IFS=$'\t' read -r fqn kind file line depth; do
    i=$((i + 1))
    [[ "$i" -gt "$BLAST_CAP" ]] && break
    printf '| `%s` | %s | `%s:%s` | %s |\n' "$(md_escape "$fqn")" "$kind" "$(md_escape "$file")" "$line" "$depth"
  done < <(jq -r '(.blast_radius // [])[] | [(.fqn // .symbol), .kind, .file, .start_line, .depth] | @tsv' "$REVIEW_JSON")
  if [[ "$blast_radius_count" -gt "$BLAST_CAP" ]]; then
    echo
    echo "_+$((blast_radius_count - BLAST_CAP)) more (deeper) node(s) not shown._"
  fi
  echo
}

render_untested() {
  if [[ "$changed_symbols_count" -eq 0 ]]; then
    return
  fi
  if [[ "$untested_count" -eq 0 ]]; then
    if [[ "$analysis_complete" == "true" && "$call_graph" == "resolved" ]]; then
      echo "**Untested**: none — every changed symbol has at least one covering test in its blast radius."
    elif [[ "$analysis_complete" == "true" && "$call_graph" == "name" ]]; then
      echo "**Untested**: none reported by the name-based graph — coverage is a medium-confidence candidate and may over- or under-report same-named/dynamic relationships. Run precise indexing to confirm."
    elif [[ "$analysis_complete" == "true" ]]; then
      echo "**Untested**: unknown — none reported, but test coverage cannot be established while call graph resolution is \`${call_graph:-unknown}\`."
    else
      echo "**Untested**: none reported in the analyzed subset — incomplete analysis cannot establish coverage for every changed symbol."
    fi
    echo
    return
  fi
  echo "**⚠️ Untested** (${untested_count} changed symbol(s) with no covering test):"
  echo
  local i=0
  while IFS=$'\t' read -r fqn kind file line; do
    i=$((i + 1))
    [[ "$i" -gt "$UNTESTED_CAP" ]] && break
    printf -- '- `%s` (%s) — `%s:%s`\n' "$(md_escape "$fqn")" "$kind" "$(md_escape "$file")" "$line"
  done < <(jq -r '(.untested_symbols // [])[] | [(.fqn // .symbol), .kind, .file, .start_line] | @tsv' "$REVIEW_JSON")
  if [[ "$untested_count" -gt "$UNTESTED_CAP" ]]; then
    echo "- _+$((untested_count - UNTESTED_CAP)) more not shown._"
  fi
  echo
}

render_hotspots() {
  if [[ "$hotspots_count" -eq 0 ]]; then
    return
  fi
  echo "**Hotspots** (${hotspots_count} changed symbol(s) with many direct callers):"
  echo
  local i=0
  while IFS=$'\t' read -r fqn kind file line; do
    i=$((i + 1))
    [[ "$i" -gt "$HOTSPOTS_CAP" ]] && break
    printf -- '- `%s` (%s) — `%s:%s`\n' "$(md_escape "$fqn")" "$kind" "$(md_escape "$file")" "$line"
  done < <(jq -r '(.hotspots // [])[] | [(.fqn // .symbol), .kind, .file, .start_line] | @tsv' "$REVIEW_JSON")
  if [[ "$hotspots_count" -gt "$HOTSPOTS_CAP" ]]; then
    echo "- _+$((hotspots_count - HOTSPOTS_CAP)) more not shown._"
  fi
  echo
}

render_risk() {
  if [[ "$risk_present" != "true" ]]; then
    echo "**Risk**: not computed — this diff touched no indexed symbols."
    echo
    return
  fi
  local level score
  level="$(j '.risk.level')"
  score="$(j '.risk.score')"
  local emoji="⚪"
  case "$level" in
    high) emoji="🔴" ;;
    medium) emoji="🟠" ;;
    low) emoji="🟢" ;;
    unknown) emoji="⚪" ;;
  esac
  echo "**Risk**: ${emoji} \`${level}\` (score ${score})"
  echo
  local factor_count
  factor_count="$(j '(.risk.factors // []) | length')"
  if [[ "$factor_count" -gt 0 ]]; then
    echo "| Factor | Severity | Detail |"
    echo "|---|---|---|"
    while IFS=$'\t' read -r factor severity detail; do
      printf '| %s | %s | %s |\n' "$factor" "$severity" "$(md_escape "$detail")"
    done < <(jq -r '(.risk.factors // [])[] | [.factor, .severity, .detail] | @tsv' "$REVIEW_JSON")
  fi
  echo
}

render_test_commands() {
  if [[ "$test_commands_count" -eq 0 ]]; then
    return
  fi
  echo "**Test commands**"
  echo
  echo '```bash'
  jq -r '(.test_commands // [])[]' "$REVIEW_JSON"
  echo '```'
  echo
}

render_caveats() {
  local lines=()
  case "$call_graph" in
    name)
      lines+=("call graph resolution is \`name\` (not \`resolved\`) — Go name matching is medium-confidence candidate evidence and may over-match same-named methods or miss dynamic wiring. Run with \`precise: true\` to confirm edges via \`go/types\`.")
      ;;
    unresolved)
      lines+=("call graph resolution is \`unresolved\` — blast radius and test coverage are unknown, not empty. Run with \`precise: true\` and install the relevant language server (\`install-ts-language-server\`/\`install-pyright\`) for exact edges.")
      ;;
    none)
      lines+=("call graph resolution is \`none\` — no usable call relationship evidence was available for the mapped symbols.")
      ;;
  esac
  if [[ -n "$resolution" ]]; then
    lines+=("$resolution")
  fi
  if [[ "$stale" == "true" ]]; then
    local c n d
    c="$(j '.staleness.changed // 0')"
    n="$(j '.staleness.new // 0')"
    d="$(j '.staleness.deleted // 0')"
    lines+=("the index is **stale** (changed: ${c}, new: ${n}, deleted: ${d}) — refresh it before trusting this report.")
  fi
  if [[ "$deletion_present" == "true" ]]; then
    local df da dm dc
    df="$(j '.deletion_analysis.files // 0')"
    da="$(j '.deletion_analysis.analyzed // 0')"
    dm="$(j '.deletion_analysis.missing // 0')"
    dc="$(j '.deletion_analysis.complete // false')"
    lines+=("this diff deletes ${df} file(s); ${da} analyzed from the last indexed snapshot, ${dm} missing (complete: ${dc}) — run selected tests before reindexing prunes that evidence.")
  fi
  if [[ -n "$note" ]]; then
    lines+=("$note")
  fi
  if [[ "${#lines[@]}" -eq 0 ]]; then
    return
  fi
  echo "**Caveats**"
  echo
  for l in "${lines[@]}"; do
    printf -- '- %s\n' "$l"
  done
  echo
}

render_footer() {
  echo "$MARKER"
  echo "<sub>generated by codemap-action ${ACTION_VERSION} · commit \`${COMMIT_SHA}\`</sub>"
}

# --- assemble -----------------------------------------------------------
build() {
  local drop_blast="${1:-false}" drop_symbols="${2:-false}" drop_files="${3:-false}"
  {
    render_header
    render_analysis_warning
    if render_not_repo_or_indexed; then
      render_footer
      return
    fi
    if [[ "$drop_files" == "true" ]]; then
      echo "**Files touched**: ${changed_files_count} (list omitted to stay under the comment size limit)"
      echo
    else
      render_changed_files
    fi
    if [[ "$drop_symbols" == "true" ]]; then
      echo "**Changed symbols**: ${changed_symbols_count} (list omitted to stay under the comment size limit)"
      echo
    else
      render_changed_symbols
    fi
    if [[ "$drop_blast" == "true" ]]; then
      echo "**Blast radius**: ${blast_radius_count} symbol(s) reachable from this diff, ${covering_tests_count} covering test(s) (list omitted to stay under the comment size limit)"
      echo
    else
      render_blast_radius
    fi
    render_untested
    render_hotspots
    render_risk
    render_test_commands
    render_caveats
    render_footer
  }
}

body="$(build false false false)"
if [[ "$(printf '%s' "$body" | wc -c | tr -d ' ')" -gt "$MAX_BYTES" ]]; then
  body="$(build true false false)"
fi
if [[ "$(printf '%s' "$body" | wc -c | tr -d ' ')" -gt "$MAX_BYTES" ]]; then
  body="$(build true true false)"
fi
if [[ "$(printf '%s' "$body" | wc -c | tr -d ' ')" -gt "$MAX_BYTES" ]]; then
  body="$(build true true true)"
fi
size="$(printf '%s' "$body" | wc -c | tr -d ' ')"
if [[ "$size" -gt "$MAX_BYTES" ]]; then
  echo "::warning::rendered comment is ${size} bytes, still over the ${MAX_BYTES}-byte soft cap even after dropping all list sections (analysis/risk/untested headlines are never truncated) — GitHub's hard limit is 65536 bytes"
fi

printf '%s\n' "$body" > "$OUT"
emit_output "$OUT"
echo "codemap-action: rendered comment to ${OUT} (${size} bytes)"
